# Generated by Django 5.1 on 2024-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.PositiveIntegerField()),
                ('phone1', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
