# Generated by Django 5.1 on 2024-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the book', max_length=40, null=True)),
                ('price', models.PositiveIntegerField()),
                ('isbn_no', models.CharField(max_length=40, unique=True)),
                ('author', models.CharField(blank=True, max_length=80, null=True)),
                ('published_date', models.DateField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
